In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [186]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [187]:
cancer["data"]

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [188]:
cancer["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [189]:
print(cancer['DESCR'])  #dataset description

Breast Cancer Wisconsin (Diagnostic) Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, field
        13 is Radius SE, field 23 is Worst Radius.

        

In [190]:
x = cancer['data']
y = cancer['target']

In [191]:
x_df = pd.DataFrame(x)
x_df.head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9    ...        20     21      22      23      24      25      26  \
0  0.07871   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.05667   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.05999   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.09744   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.05883   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   

       27      28       29  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  

[5 rows x 30 columns]

In [192]:
y_df = pd.DataFrame(y)
y_df.tail(10)

0
559  1
560  1
561  1
562  0
563  0
564  0
565  0
566  0
567  0
568  1

In [193]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [194]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scalar.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [195]:
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

In [196]:
x_train_df = pd.DataFrame(x_train)
x_train_df.head()

0         1         2         3         4         5         6   \
0 -0.551942 -1.217228 -0.601985 -0.545391 -1.348060 -1.349379 -0.942629   
1 -0.480943 -0.524105 -0.546601 -0.500484 -1.473814 -1.303722 -0.915944   
2  0.632331  0.968958  0.700578  0.525034  0.078583  0.868958  1.127235   
3 -0.151504 -0.324713 -0.233165 -0.232171 -1.196017 -1.190899 -0.836132   
4 -0.472423  1.146986 -0.326293 -0.504438  1.583378  2.565068  1.690182   

         7         8         9     ...           20        21        22  \
0 -1.105436 -0.526179 -0.904193    ...    -0.707878 -1.511653 -0.760570   
1 -0.802860 -1.260124 -1.032698    ...    -0.697463 -0.895878 -0.755807   
2  0.989939  1.306856 -0.073292    ...     0.652361  0.885590  0.659558   
3 -0.919694 -0.891326 -1.092569    ...    -0.155867  0.073886 -0.245216   
4  0.931649  0.777393  2.883782    ...    -0.241272  2.474422 -0.282728   

         23        24        25        26        27        28        29  
0 -0.641566 -1.414444 -1.246487 -1.085840 -1.438071 -1.010678 -1.297682  
1 -0.636650 -2.119067 -1.285533 -1.175378 -1.290022 -1.673347 -1.356853  
2  0.502943  0.407628  1.355637  2.095121  1.678204  3.267931  0.718082  
3 -0.244789 -1.198788 -1.102267 -0.776864 -0.934554 -0.939678 -1.170323  
4 -0.293420  2.335328  5.080784  3.983570  1.620798  2.493691  6.993605  

[5 rows x 30 columns]

In [197]:
from sklearn.neural_network import MLPClassifier #multilevel perceptron


In [198]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30,30,30,30,30,30))

In [199]:
mlp.fit(x_train,y_train) #training of neural network model

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(30, 30, 30, 30, 30, 30, 30, 30),
       learning_rate='constant', learning_rate_init=0.001, max_iter=200,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [200]:
predictions = mlp.predict(x_test)

In [201]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predictions))

[[56  3]
 [ 1 83]]


In [202]:
from sklearn.metrics import accuracy_score
accuracy_nn=round(accuracy_score(predictions,y_test)*100,2)
print("Accuracy of this model is ",accuracy_nn,"%")

Accuracy of this model is  97.2 %


In [205]:
from sklearn.ensemble import RandomForestClassifier

model_rand=RandomForestClassifier(n_estimators=100)
model_rand.fit(x_train,y_train)

predicted_rand=model_rand.predict(x_test)

from sklearn.metrics import confusion_matrix 
print(confusion_matrix(predicted_rand,y_test))

from sklearn.metrics import accuracy_score

accuracy=round(accuracy_score(predicted_rand,y_test)*100,2)
print("Accuracy of this model is ",accuracy,"%")

[[53  3]
 [ 6 81]]
Accuracy of this model is  93.71 %
